-- Run this in the Supabase SQL Editor to create the shared invoice pool table.
-- Mirrors the local SQLite `eta_invoices` table so the pool can be shared
-- across all users (claims, used status, and delete requests).

create table if not exists public.pool_invoices (
  id bigint generated by default as identity primary key,
  invoice_id text not null unique,
  uuid text not null default '',
  seller_tax_id text not null default '',
  seller_name text not null default '',
  buyer_tax_id text not null default '',
  buyer_name text not null default '',
  issue_date text not null default '',
  currency text not null default '',
  net_amount double precision not null default 0,
  total_vat double precision not null default 0,
  total_wht double precision not null default 0,
  grand_total double precision not null default 0,
  lines_json text not null default '[]',
  raw_xml text not null default '',
  file_name text not null default '',
  status text not null default 'available',
  used_by_label text not null default '',
  delete_requested_at timestamptz,
  delete_requested_by text,
  created_at timestamptz not null default now(),
  constraint pool_invoices_invoice_id_key unique (invoice_id)
);

alter table public.pool_invoices enable row level security;

-- All authenticated users can read and write the shared pool.
create policy "pool read" on public.pool_invoices
  for select to authenticated using (true);

create policy "pool insert" on public.pool_invoices
  for insert to authenticated with check (true);

create policy "pool update" on public.pool_invoices
  for update to authenticated using (true);

create policy "pool delete" on public.pool_invoices
  for delete to authenticated using (true);