-- Run this in the Supabase SQL Editor to create the shared invoice pool table.
-- Mirrors the local SQLite `eta_invoices` table so the pool can be shared
-- across all users (claims, used status, and delete requests).

-- Identity: an invoice is one ETA document, uniquely identified by its `uuid`.
-- The same (invoice_id, seller_tax_id) may exist multiple times when a supplier
-- resubmits a corrected invoice under a new attempt uuid; a rejected/cancelled
-- attempt must never overwrite or collide with the valid one. The unique index
-- on `uuid` therefore lives on the cloud too, so upserts keyed by uuid converge
-- correctly. PostgREST cannot upsert against partial unique indexes, so the
-- cloud index is NON-partial: every row must carry a non-empty unique uuid
-- (invoices with no uuid get one backfilled from their id below).
create table if not exists public.pool_invoices (
  id bigint generated by default as identity primary key,
  invoice_id text not null default '',
  uuid text not null default '',
  seller_tax_id text not null default '',
  seller_name text not null default '',
  buyer_tax_id text not null default '',
  buyer_name text not null default '',
  issue_date text not null default '',
  currency text not null default '',
  net_amount double precision not null default 0,
  total_vat double precision not null default 0,
  total_wht double precision not null default 0,
  grand_total double precision not null default 0,
  lines_json text not null default '[]',
  raw_xml text not null default '',
  file_name text not null default '',
  doc_status text not null default 'Valid',
  status text not null default 'available',
  used_by_label text not null default '',
  delete_requested_at timestamptz,
  delete_requested_by text,
  created_at timestamptz not null default now()
);

-- Migration for tables created before doc_status existed (v0.3.23):
alter table public.pool_invoices add column if not exists doc_status text not null default 'Valid';

alter table public.pool_invoices enable row level security;

-- All authenticated users can read and write the shared pool.
create policy "pool read" on public.pool_invoices
  for select to authenticated using (true);

create policy "pool insert" on public.pool_invoices
  for insert to authenticated with check (true);

create policy "pool update" on public.pool_invoices
  for update to authenticated using (true);

create policy "pool delete" on public.pool_invoices
  for delete to authenticated using (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- v0.3.30 MIGRATION: switch pool identity from (invoice_id, seller_tax_id) to
-- the ETA document uuid.
--
-- Run this block ONCE against existing cloud data (it is idempotent). It:
--   1. backfills a non-empty unique uuid for any legacy rows that lack one,
--   2. drops the old composite unique index (and the original invoice_id unique
--      constraint if that old version of the table is still present),
--   3. creates the NON-partial unique index on uuid that upserts rely on.
--
-- NOTE: several hundred rows may already share the empty '' uuid; the backfill
-- maps each to 'legacy-<id>' so the unique index can be created without
-- violating uniqueness. New app versions always write a real uuid, so these
-- legacy ids are never in conflict.
-- ─────────────────────────────────────────────────────────────────────────────
update public.pool_invoices set uuid = 'legacy-' || id::text
where uuid is null or uuid = '';

alter table public.pool_invoices drop constraint if exists pool_invoices_invoice_id_key;
drop index if exists idx_eta_invoice_seller;
drop index if exists idx_eta_invoice_id;

create unique index if not exists idx_pool_invoices_uuid on public.pool_invoices (uuid);